export const ADD_TODO = 'ADD_TODO';

export const COMPLETE_TODO = 'COMPLETE_TODO';

export const GET_INITIAL_TODOS_PENDING = 'GET_INITIAL_TODOS_PENDING';
export const GET_INITIAL_TODOS_REJECTED = 'GET_INITIAL_TODOS_REJECTED';
export const GET_INITIAL_TODOS_FULFILLED = 'GET_INITIAL_TODOS_FULFILLED';

export const DELETE_TODO = 'DELETE_TODO';
